# schema
[settings]
experimental = true
env_shell_expand = true

[tools]
actionlint = "latest"
hadolint = "latest"
hk = { version = "1.41", arch = "aarch64" }
"nix:nixfmt" = "1.2.0"
"npm:semantic-release" = "latest"
"pipx:commitizen" = "latest"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
tombi = "latest"

[env]
HK_MISE = 1

[hooks]
postinstall = "command -v hk >/dev/null && hk install --mise || true"
