FROM docker.io/nixos/nix:latest

LABEL org.opencontainers.image.description="A Linux Builder for nix-darwin using Apple Containers. Uses an OverlayFS to persist nix store builds and cache" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.url="https://github.com"

ENV NIX_PATH=""

RUN nix --extra-experimental-features "nix-command flakes" profile add nixpkgs#util-linux \
 && mkdir -p /var/empty /run/sshd /etc/ssh /var/cache/nix/narinfo
